# Generated by Django 5.2.7 on 2025-10-10 15:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance'), ('ERROR', 'Error')], default='ACTIVE', max_length=20)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('installed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='monitoring.location')),
            ],
            options={
                'ordering': ['sensor_id'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('pm25', models.FloatField(help_text='PM2.5 concentration (µg/m³)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)])),
                ('pm10', models.FloatField(help_text='PM10 concentration (µg/m³)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)])),
                ('co', models.FloatField(help_text='Carbon Monoxide concentration (ppm)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('no2', models.FloatField(help_text='Nitrogen Dioxide concentration (ppb)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)])),
                ('so2', models.FloatField(help_text='Sulfur Dioxide concentration (ppb)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)])),
                ('o3', models.FloatField(help_text='Ozone concentration (ppb)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)])),
                ('temperature', models.FloatField(blank=True, help_text='Temperature (°C)', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Humidity (%)', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind Speed (m/s)', null=True)),
                ('wind_direction', models.FloatField(blank=True, help_text='Wind Direction (degrees)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AQICalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aqi_pm25', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)])),
                ('aqi_pm10', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)])),
                ('aqi_co', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)])),
                ('aqi_no2', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)])),
                ('aqi_so2', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)])),
                ('aqi_o3', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)])),
                ('overall_aqi', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)])),
                ('aqi_status', models.CharField(choices=[('GOOD', 'Good'), ('MODERATE', 'Moderate'), ('UNHEALTHY_SG', 'Unhealthy for Sensitive Groups'), ('UNHEALTHY', 'Unhealthy'), ('VERY_UNHEALTHY', 'Very Unhealthy'), ('HAZARDOUS', 'Hazardous')], max_length=20)),
                ('dominant_pollutant', models.CharField(max_length=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('sensor_reading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aqi_calculation', to='monitoring.sensorreading')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_aqi_threshold', models.FloatField(blank=True, null=True)),
                ('custom_pm25_threshold', models.FloatField(blank=True, null=True)),
                ('custom_pm10_threshold', models.FloatField(blank=True, null=True)),
                ('notification_method', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('NONE', 'No Notifications')], default='NONE', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('update_frequency_minutes', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='monitoring.location')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('AQI_THRESHOLD', 'AQI Threshold Exceeded'), ('POLLUTANT_SPIKE', 'Pollutant Spike'), ('SENSOR_OFFLINE', 'Sensor Offline'), ('DATA_ANOMALY', 'Data Anomaly')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('EMERGENCY', 'Emergency')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('pollutant', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aqi_calculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.aqicalculation')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.sensor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sensor', '-created_at'], name='monitoring__sensor__a1b40c_idx'), models.Index(fields=['severity', 'is_active'], name='monitoring__severit_604c1e_idx'), models.Index(fields=['alert_type'], name='monitoring__alert_t_b20e11_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['sensor', '-timestamp'], name='monitoring__sensor__fd56b6_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['timestamp'], name='monitoring__timesta_6f0ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='aqicalculation',
            index=models.Index(fields=['-calculated_at'], name='monitoring__calcula_2aa51f_idx'),
        ),
        migrations.AddIndex(
            model_name='aqicalculation',
            index=models.Index(fields=['aqi_status'], name='monitoring__aqi_sta_840142_idx'),
        ),
        migrations.AddIndex(
            model_name='aqicalculation',
            index=models.Index(fields=['overall_aqi'], name='monitoring__overall_9eae11_idx'),
        ),
    ]
